const MANCHESTER = '2643534';
const SCOTLAND = '2163145';
const LONDON = '2581155';

module.exports = {

    'MANCHESTER': MANCHESTER,
    'MANCHESTER, UK': MANCHESTER,
    'MANCHECTER': MANCHESTER,
    'DONCASTER': MANCHESTER,
    'LIVERPOOL': MANCHESTER,
    'BOLTON': MANCHESTER,
    'ROCHDALE': MANCHESTER,
    'WIGAN': MANCHESTER,
    'ASHTON-UNDER-LYNE': MANCHESTER,
    'STOCKPORT': MANCHESTER,
    'GREATER MANCHESTER': MANCHESTER,
    'GREAT MANCHESTER': MANCHESTER,
    'SHEFFIELD': MANCHESTER,
    'LEEDS': MANCHESTER,
    'WIDNES': MANCHESTER,
    'HUDDERSFIELD': MANCHESTER,

    'LONDON': LONDON,
    'LONDON, UK': LONDON,
    'LUTON': LONDON,
    'EAST LONDON': LONDON,
    'NW LONDON': LONDON,
    'PECKHAM, LONDON': LONDON,
    'STRATFORD, LONDON': LONDON,
    'ILFORD, LONDON': LONDON,
    'HAMPTON COURT': LONDON,

    'SCOTLAND': SCOTLAND,
    'SCOTLAND, UK': SCOTLAND,
    'GLASGOW': SCOTLAND,
    'GLASGOW, UK': SCOTLAND,
    'GLAGOW': SCOTLAND,
    'EDINBURGH': SCOTLAND,
    'BRIGHTON': SCOTLAND,

};